[2024-05-12T13:43:01.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T13:43:01.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.load manual__2024-05-12T13:35:17.690852+00:00 [queued]>
[2024-05-12T13:43:01.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.load manual__2024-05-12T13:35:17.690852+00:00 [queued]>
[2024-05-12T13:43:01.353+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T13:43:01.363+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-12 13:35:17.690852+00:00
[2024-05-12T13:43:01.367+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2733) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T13:43:01.369+0000] {standard_task_runner.py:63} INFO - Started process 2735 to run task
[2024-05-12T13:43:01.369+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'load', 'manual__2024-05-12T13:35:17.690852+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpah2ap_x8']
[2024-05-12T13:43:01.370+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask load
[2024-05-12T13:43:01.405+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.load manual__2024-05-12T13:35:17.690852+00:00 [running]> on host 8b349270b58a
[2024-05-12T13:43:01.468+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T13:35:17.690852+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T13:35:17.690852+00:00'
[2024-05-12T13:43:01.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T13:43:01.486+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T13:43:01.486+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mlops_dag.py", line 126, in <lambda>
    python_callable=lambda: load(transform(data)),
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mlops_dag.py", line 100, in load
    df = df.dropna(subset=['title', 'description'])  # Ensure data completeness
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6418, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['title', 'description']
[2024-05-12T13:43:01.501+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=load, run_id=manual__2024-05-12T13:35:17.690852+00:00, execution_date=20240512T133517, start_date=20240512T134301, end_date=20240512T134301
[2024-05-12T13:43:01.510+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task load (['title', 'description']; 2735)
[2024-05-12T13:43:01.543+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T13:43:01.560+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T13:43:01.564+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
