[2024-05-12T16:42:57.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:42:57.567+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:42:40.762770+00:00 [queued]>
[2024-05-12T16:42:57.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:42:40.762770+00:00 [queued]>
[2024-05-12T16:42:57.579+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T16:42:57.592+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 16:42:40.762770+00:00
[2024-05-12T16:42:57.598+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=354) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T16:42:57.600+0000] {standard_task_runner.py:63} INFO - Started process 356 to run task
[2024-05-12T16:42:57.600+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T16:42:40.762770+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmp8gwk7n1k']
[2024-05-12T16:42:57.601+0000] {standard_task_runner.py:91} INFO - Job 162: Subtask dvc_add_and_push
[2024-05-12T16:42:57.642+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:42:40.762770+00:00 [running]> on host e6e483b741f2
[2024-05-12T16:42:57.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:42:40.762770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:42:40.762770+00:00'
[2024-05-12T16:42:57.704+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:42:57.705+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T16:42:57.706+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ncd /opt/***/dags\ndvc init -f --no-scm && dvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE -f && dvc add extracted_data.csv && dvc push -r mygoogleDrive']
[2024-05-12T16:42:57.718+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T16:42:58.624+0000] {subprocess.py:93} INFO - Initialized DVC repository.
[2024-05-12T16:42:58.624+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:42:58.628+0000] {subprocess.py:93} INFO - +---------------------------------------------------------------------+
[2024-05-12T16:42:58.628+0000] {subprocess.py:93} INFO - |                                                                     |
[2024-05-12T16:42:58.629+0000] {subprocess.py:93} INFO - |        DVC has enabled anonymous aggregate usage analytics.         |
[2024-05-12T16:42:58.629+0000] {subprocess.py:93} INFO - |     Read the analytics documentation (and how to opt-out) here:     |
[2024-05-12T16:42:58.630+0000] {subprocess.py:93} INFO - |             <https://dvc.org/doc/user-guide/analytics>              |
[2024-05-12T16:42:58.631+0000] {subprocess.py:93} INFO - |                                                                     |
[2024-05-12T16:42:58.632+0000] {subprocess.py:93} INFO - +---------------------------------------------------------------------+
[2024-05-12T16:42:58.632+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:42:58.633+0000] {subprocess.py:93} INFO - What's next?
[2024-05-12T16:42:58.633+0000] {subprocess.py:93} INFO - ------------
[2024-05-12T16:42:58.634+0000] {subprocess.py:93} INFO - - Check out the documentation: <https://dvc.org/doc>
[2024-05-12T16:42:58.634+0000] {subprocess.py:93} INFO - - Get help and share ideas: <https://dvc.org/chat>
[2024-05-12T16:42:58.635+0000] {subprocess.py:93} INFO - - Star us on GitHub: <https://github.com/iterative/dvc>
[2024-05-12T16:42:59.471+0000] {subprocess.py:93} INFO - Setting 'mygoogledrive' as a default remote.
[2024-05-12T16:43:02.192+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/***/.cache/pydrive2fs/710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com/default.json: No such file or directory
[2024-05-12T16:43:02.193+0000] {subprocess.py:93} INFO -   warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
[2024-05-12T16:43:02.193+0000] {subprocess.py:93} INFO - Your browser has been opened to visit:
[2024-05-12T16:43:02.194+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:43:02.194+0000] {subprocess.py:93} INFO -     https://accounts.google.com/o/oauth2/auth?client_id=710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force
[2024-05-12T16:43:02.195+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:51:57.395+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-05-12T16:51:57.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-12T16:51:57.397+0000] {process_utils.py:132} INFO - Sending 15 to group 356. PIDs of all processes in the group: [357, 356]
[2024-05-12T16:51:57.398+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 356
[2024-05-12T16:51:57.399+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-12T16:51:57.399+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-05-12T16:51:57.400+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:51:57.425+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=357, status='terminated', started='16:42:57') (357) terminated with exit code None
[2024-05-12T16:51:57.426+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=356, status='terminated', exitcode=0, started='16:42:57') (356) terminated with exit code 0
