[2024-05-12T14:42:24.952+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T14:42:24.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.load manual__2024-05-12T14:42:14.463476+00:00 [queued]>
[2024-05-12T14:42:24.976+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.load manual__2024-05-12T14:42:14.463476+00:00 [queued]>
[2024-05-12T14:42:24.977+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T14:42:24.991+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-12 14:42:14.463476+00:00
[2024-05-12T14:42:24.996+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3547) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T14:42:24.997+0000] {standard_task_runner.py:63} INFO - Started process 3549 to run task
[2024-05-12T14:42:24.997+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'load', 'manual__2024-05-12T14:42:14.463476+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpb9_ntfd2']
[2024-05-12T14:42:24.999+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask load
[2024-05-12T14:42:25.038+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.load manual__2024-05-12T14:42:14.463476+00:00 [running]> on host 8b349270b58a
[2024-05-12T14:42:25.100+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T14:42:14.463476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T14:42:14.463476+00:00'
[2024-05-12T14:42:25.102+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T14:42:26.610+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/world-europe-68998913
[2024-05-12T14:42:26.611+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/world-europe-68998913
[2024-05-12T14:42:26.778+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/uk-politics-68999212
[2024-05-12T14:42:26.779+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/uk-politics-68999212
[2024-05-12T14:42:26.945+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/world-europe-68998913
[2024-05-12T14:42:26.947+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/world-europe-68998913
[2024-05-12T14:42:27.113+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/uk-politics-68999212
[2024-05-12T14:42:27.114+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/uk-politics-68999212
[2024-05-12T14:42:27.282+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/articles/c72p0xx410xo
[2024-05-12T14:42:27.283+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/articles/c72p0xx410xo
[2024-05-12T14:42:27.450+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/world-us-canada-68996066
[2024-05-12T14:42:27.452+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/world-us-canada-68996066
[2024-05-12T14:42:27.622+0000] {mlops_dag.py:33} WARNING - No valid title or description for URL: https://www.bbc.com/news/world-us-canada-68991796
[2024-05-12T14:42:27.624+0000] {mlops_dag.py:77} INFO - No data extracted for https://www.bbc.com/news/world-us-canada-68991796
[2024-05-12T14:42:27.984+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T14:42:27.985+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mlops_dag.py", line 135, in <lambda>
    python_callable=lambda: load(transform(extract())),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mlops_dag.py", line 110, in load
    df.to_csv('C:/Users/shaklu/Desktop/MLOPsAssignment2/extracted_data.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/Users/shaklu/Desktop/MLOPsAssignment2'
[2024-05-12T14:42:27.996+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=load, run_id=manual__2024-05-12T14:42:14.463476+00:00, execution_date=20240512T144214, start_date=20240512T144224, end_date=20240512T144227
[2024-05-12T14:42:28.009+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task load (Cannot save file into a non-existent directory: 'C:/Users/shaklu/Desktop/MLOPsAssignment2'; 3549)
[2024-05-12T14:42:28.063+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T14:42:28.080+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T14:42:28.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
