[2024-05-12T16:39:18.206+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:39:18.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:38:31.879942+00:00 [queued]>
[2024-05-12T16:39:18.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:38:31.879942+00:00 [queued]>
[2024-05-12T16:39:18.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T16:39:18.251+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 16:38:31.879942+00:00
[2024-05-12T16:39:18.257+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T16:39:18.258+0000] {standard_task_runner.py:63} INFO - Started process 116 to run task
[2024-05-12T16:39:18.258+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T16:38:31.879942+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmptvolee4w']
[2024-05-12T16:39:18.260+0000] {standard_task_runner.py:91} INFO - Job 153: Subtask dvc_add_and_push
[2024-05-12T16:39:18.307+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:38:31.879942+00:00 [running]> on host e6e483b741f2
[2024-05-12T16:39:18.387+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:38:31.879942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:38:31.879942+00:00'
[2024-05-12T16:39:18.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:39:18.389+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T16:39:18.390+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ncd /opt/***/dags\ndvc init -f --no-scm && dvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE && dvc add extracted_data.csv && dvc push -r mygoogleDrive']
[2024-05-12T16:39:18.450+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T16:39:21.494+0000] {subprocess.py:93} INFO - Initialized DVC repository.
[2024-05-12T16:39:21.495+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:39:21.499+0000] {subprocess.py:93} INFO - +---------------------------------------------------------------------+
[2024-05-12T16:39:21.500+0000] {subprocess.py:93} INFO - |                                                                     |
[2024-05-12T16:39:21.500+0000] {subprocess.py:93} INFO - |        DVC has enabled anonymous aggregate usage analytics.         |
[2024-05-12T16:39:21.501+0000] {subprocess.py:93} INFO - |     Read the analytics documentation (and how to opt-out) here:     |
[2024-05-12T16:39:21.501+0000] {subprocess.py:93} INFO - |             <https://dvc.org/doc/user-guide/analytics>              |
[2024-05-12T16:39:21.501+0000] {subprocess.py:93} INFO - |                                                                     |
[2024-05-12T16:39:21.502+0000] {subprocess.py:93} INFO - +---------------------------------------------------------------------+
[2024-05-12T16:39:21.503+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:39:21.504+0000] {subprocess.py:93} INFO - What's next?
[2024-05-12T16:39:21.504+0000] {subprocess.py:93} INFO - ------------
[2024-05-12T16:39:21.504+0000] {subprocess.py:93} INFO - - Check out the documentation: <https://dvc.org/doc>
[2024-05-12T16:39:21.505+0000] {subprocess.py:93} INFO - - Get help and share ideas: <https://dvc.org/chat>
[2024-05-12T16:39:21.505+0000] {subprocess.py:93} INFO - - Star us on GitHub: <https://github.com/iterative/dvc>
[2024-05-12T16:39:22.535+0000] {subprocess.py:93} INFO - Setting 'mygoogledrive' as a default remote.
[2024-05-12T16:39:27.968+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/***/.cache/pydrive2fs/710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com/default.json: No such file or directory
[2024-05-12T16:39:27.969+0000] {subprocess.py:93} INFO -   warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
[2024-05-12T16:39:27.969+0000] {subprocess.py:93} INFO - Your browser has been opened to visit:
[2024-05-12T16:39:27.969+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:39:27.970+0000] {subprocess.py:93} INFO -     https://accounts.google.com/o/oauth2/auth?client_id=710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force
[2024-05-12T16:39:27.970+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:42:45.717+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-05-12T16:42:45.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-12T16:42:45.719+0000] {process_utils.py:132} INFO - Sending 15 to group 116. PIDs of all processes in the group: [117, 116]
[2024-05-12T16:42:45.720+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 116
[2024-05-12T16:42:45.721+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-12T16:42:45.721+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-05-12T16:42:45.722+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:42:45.773+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=117, status='terminated', started='16:39:18') (117) terminated with exit code None
[2024-05-12T16:42:45.774+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=116, status='terminated', exitcode=0, started='16:39:17') (116) terminated with exit code 0
